name: leakguard_mq2
description: Projeto LeakGuard - Console com integração ESP32, Firebase e MySQL.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  http: ^0.13.5           # Comunicação com Firebase
  mysql1: ^0.20.0         # Conexão e consultas MySQL
  intl: ^0.19.0           # Formatação de datas e números
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
